id: I88D3D389
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:49:54+00:00'
last_modified: '2022-06-08T09:58:33.302650+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN50
  title: བླ་མ་ཡང་ཏིག་ཡིད་བཞིན་ནོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6281':
      image_group_id: I3CN52
      title: ''
      total_pages: 808
      order: 1
      base_file: 6281.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
